<a href="https://colab.research.google.com/github/Phi142/Bai-tap-1-Tren-Lop/blob/main/tuan08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install Perception


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 6.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19579 sha256=ee61ee337f90d6b0ddb8530a1d446956810b0d9fab67219dc9e33ae953eb2890
  Stored in directory: /root/.cache/pip/wheels/2d/f0/a8/1094fca7a7e5d0d12ff56e0c64675d72aa5cc81a5fc200e849
Successfully built validators


In [ ]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

Making "NOT" gate

In [ ]:
x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]
model = Perceptron()
model.fit(x, t)
model.score(x, t)

In [ ]:
x1 = [[0.5, 1],[0.5, 0.5],[-10, 1]]
y1 = model.predict(x1)
print(y1)
model.score(x1, y1)

[0 0 1]


1.0

Another Test

In [ ]:
x = [[-0.5,-0.5],[-0.5,0.5],[0.5,0.5],[-0.5,1]]
t = [1,1,0,0]
model = Perceptron()
model.fit(x, t)
model.score(x, t)

In [ ]:
x1 = [[-0.5, -2],[-5, 7],[-10, 99999]]
y1 = model.predict(x1)
print(y1)
model.score(x1, y1)

[1 0 0]


1.0

One hot Encoding

In [ ]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from numpy.core.fromnumeric import shape

iris = datasets.load_iris()
shape(iris)
print(iris)

In [ ]:
x = iris.data
y = iris.target
print(x[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
model = Perceptron(max_iter = 50, eta0 = 0.1, random_state = 0)  #toc do hoc la so duong nho hon 1
model.fit(x_train_std, y_train)  #so lan hoc
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test, y_pred))

[1 0 0 2 0 1 1 2 1 1 0 1 2 1 2 2 2 1 2 2 1 0 2 1 1 0 0 2 0 0 2 2 2 0 1 1 1
 0 0 2 2 2 0 2 1]
[1 0 0 1 0 1 1 2 1 1 0 1 2 1 2 2 2 0 2 2 1 0 2 1 1 1 0 2 0 1 2 2 2 0 1 1 1
 0 0 2 2 2 0 2 1]
Độ chính xác của mô hình:  0.9111111111111111


In [ ]:
data = pd.read_csv('crabs.csv')
print(data.head())
print(data.shape)

data.drop(data.index[100:200],axis=0, inplace=True)
data.shape

data.replace(to_replace="M",value=0, inplace=True)
data.replace(to_replace="F",value=1, inplace=True)
data.head()

data.drop(data.columns[[0,2]], axis=1, inplace=True)
data.head()

X = data[['fontallip', 'rearwidth', 'length', 'width', 'depth']].to_numpy()
y = data['sex'].to_numpy()
#print(X)
#print(y)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

model = Perceptron(max_iter=40, eta0=0.1, random_state=0) #max_iter: số lần học, eta0: tốc độ học (càng lớn, sai số càng nhiều)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print("Do chinh xac cua mo hinh: ", accuracy_score(y_test,y_pred))

  speies sex  index  fontallip  rearwidth  length  width  depth
0      B   M      1        8.1        6.7    16.1   19.0    7.0
1      B   M      2        8.8        7.7    18.1   20.8    7.4
2      B   M      3        9.2        7.8    19.0   22.4    7.7
3      B   M      4        9.6        7.9    20.1   23.1    8.2
4      B   M      5        9.8        8.0    20.3   23.0    8.2
(200, 8)
[0 0 1 0 1 1 0 0 0 0 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1]
Do chinh xac cua mo hinh:  0.8666666666666667
